---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stash-1
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: common
    namespace: system
  driftDetection:
    mode: enabled
  upgrade:
    cleanupOnFail: true
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      stash:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/stash
              tag: 0.31.1@sha256:12c4ee1424a211888f4e4253ef70b95a639b3d5475ea3d85e88989754569537d
            env:
              STASH_STASH: /data
              STASH_BLOBS_PATH: /config/blobs
              STASH_BLOBS_STORAGE: FILESYSTEM
              STASH_GENERATED: /generated
              STASH_METADATA: /metadata
              STASH_CACHE: /cache
              STASH_PLUGINS_PATH: /config/plugins
              STASH_SCRAPERS_PATH: /config/scrapers
              STASH_CONFIG_FILE: /config/config.yml
              STASH_PORT: &port 9999
              USER: "568"
              HOME: /config
              TZ: Europe/London
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 20m
                memory: 512Mi
              limits:
                memory: 2Gi
    persistence:
      config:
        existingClaim: "stash-1-config"
        globalMounts:
          - path: /config
            subPath: config
          - path: /generated
            subPath: generated
          - path: /metadata
            subPath: metadata
      store:
        type: nfs
        server: 192.168.50.118
        path: /mnt/media/stash-rm
      tmpfs:
        type: emptyDir
        advancedMounts:
          stash:
            app:
              - path: /cache
                subPath: cache
              - path: /root/.stash/logs
                subPath: logs
              - path: /tmp
                subPath: tmp
    route:
      app:
        hostnames:
          - "stash.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      app:
        ports:
          http:
            port: *port
