---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: alertmanager-secret
  data:
    - secretKey: ALERTMANAGER_DISCORD
      remoteRef:
        key: ALERTMANAGER_DISCORD
