---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubepage-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kubepage-credentials
  data:
    - secretKey: plex-token
      remoteRef:
        key: kubepage/plex-api
    - secretKey: paperless-token
      remoteRef:
        key: kubepage/paperless-api
    - secretKey: grafana-username
      remoteRef:
        key: grafana-username
    - secretKey: grafana-password
      remoteRef:
        key: kubepage/grafana-password
    - secretKey: unifi-key
      remoteRef:
        key: kubepage/unifi-api
    - secretKey: truenas-token
      remoteRef:
        key: kubepage/truenas-api
    - secretKey: cloudflare-token
      remoteRef:
        key: kubepage/cloudflare-api
    - secretKey: linkwarden-token
      remoteRef:
        key: linkwarden-api
    - secretKey: homeassistant-token
      remoteRef:
        key: homeassistant-api
    - secretKey: mealie-token
      remoteRef:
        key: mealie-api
