---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-kubepage
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:+wfG5o/YxKHEACX3YviyubhoM8JWlaHGF1PyxUopCFyIOvrvmsHlBtUyXojWsdy7ANZ+KtrfpdWc/SxC5llq+O9QK4mRWF6owYTFGQ6nyI0zljVjfzZqS9YA8AI2fVWlbGVtO0pmE0HhWx0LADNkkslT0L2Y+yhBz+OWPwu8t6pdjdUCU6X68YVlvioEp5u1iejy/V7mOfoycGdCBQ6KzxMHPqWvBCJXJtcPfa1KhOLM8OCq6x5576N1hZhifTpOMLmP0cT0L6qOpvIONF5Bct7NOevZLTUk+cD/uTliyKKuoQOgvqnRAATNgZclLB2iE4ynIxmIrfc=,iv:9HeznefV4gl6Bli9/+xgel/KX3dG/SL3kl6xxDLaXek=,tag:vOI3u62Nil48D6AWUu2THQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlT21UVEJmZTErTHhrRXFD
        YUdXUndIMThLWUpJQ01BVnh4Tzgzem9CRGhFCk5UOHFQeDgzUGpvZitzVVhwc3RI
        eE5CL2dZRHY3OCtRSktFazRhcWxjMG8KLS0tIEtBczBPUVF1NElHVFh6dG1iVHVu
        dmkzS0NtWWJPZ29KWXIrVURoQkdxekkKTu/5vBmbwBviZBpMkrmxmhcEcsLOeRcP
        HnqGmjzXtBO4b7N+wN5LzkrZTtEg3xwkYwNvvKKQGzEm2GMfYEZ88A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-19T16:26:55Z"
  mac: ENC[AES256_GCM,data:HW2fmb2yDUHVdfCaAJ7ijV0iOie49K8Zdpfm4NJJCRU07RoiRis9cXw/rnQAIMIbGkz6ImmOY1CcgsDxQJO6/IjkbMT+FbCZ9WCN4kWKtIFSvTer/p62UnxgW6InXCuUsrho4pwn+kdetG/C4SO0vv3M4NVMW4Q6MXa/PHpLhj4=,iv:Yemtd+BeHQ/WCet8t3ppCtphEOe9CQ577enEwSM58bg=,tag:6YUSJS6ZykiD9yUcbMlQSA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
