apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:23RiU196b8c=,iv:z8eqg610Fkn4uvRs7x+SOedLrTkqZcFe1GRe21ydOdI=,tag:t2T9a0Ijg1rojG5tv6BhwQ==,type:str]
    S3URL: ENC[AES256_GCM,data:z3E/TxQ1lEjwR2LIi05qdxgI3HKUK2EA1ONbsNcL1N8xJPYOA4g=,iv:kvREqdMq+utr71pXjr84rY0BGNpkFWy9kAUVutkOcJk=,tag:V5CIlleeMf/KX0fdyAeM7g==,type:str]
    S3URL2: ENC[AES256_GCM,data:JU10A5am6VdZWIe4gh1Jk0EejEKnzSHUgVNDSdfa,iv:LunwCqT51vBTNr5+vGjTY3lyFlyvBdZmYetc6OBIdR0=,tag:a4LfFVZroKGeEJv7Rmsgpw==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:cFtCNT1QK4HAFtE=,iv:kj+kIeaRppcrhzbxp9tr3m5xBKVvwBjsu3VZBv2+dMo=,tag:8T4PselqQKPG8QjK41Tk+A==,type:str]
    S3ID: ENC[AES256_GCM,data:INDUE3kHz3xF4ns9GpAUUlOHFjnf33dgHQ==,iv:NNhy9hWNKLhOpNgy5vrBxENbTVmgTMK5inzB3YwX83Q=,tag:ZwdTP2Reiy081H3vAUWQrQ==,type:str]
    S3KEY: ENC[AES256_GCM,data:jZiLFcBkV//C4tqi8ihVeX5BxOvEF8YC60W/hhyl/Q==,iv:43GNbKNFx7KBsvu2WSdfhFrqX03T06mdWTprR1DO8kk=,tag:K4pAdXOJSrFwy4X993lETg==,type:str]
    SMTP_EMAIL: ENC[AES256_GCM,data:Q8Q2DIAOVIt+Cvdk8Hx+ac8bfA==,iv:Riw4SE9aASUStmS+VQOyj5ZM0heGiT8CZ+Jzk1Xxlpo=,tag:56Pe9DaAbY4LiyFOWkjciQ==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:1VwBi2M8lKXRGDsMBWVbXA==,iv:gN5xqrNsLUCqHLZOWplgzuViNL/c+PHbQ1tqjFBrX+k=,tag:g1ADZNjhAFnoB4kvIsiSJA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:GyL7FrSEvzqcFw==,iv:kp6ZefOkRYD3fZVj7OIE3ZzdflX/gieJTuHA4vyk0yI=,tag:smD7NtMXod/7ZoNAFNXeVw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:xgzj6utPvP3TvJKmaRlj1A==,iv:9RhNMZ53clB/CV2VqKW2h4mBUnBVVW/ZWJiEZP1s60M=,tag:gT9yHUs/PTKj+2qGgz6fcw==,type:str]
    HAOSIP: ENC[AES256_GCM,data:bnv3fuUfM1HHU5ABDg==,iv:YGkWKN/Tqb402NfOL3mVGvo14j6KlEjnHxidF6VCg4E=,tag:rxyAROrKqpC8kmmmD9iRJQ==,type:str]
    truenasip: ENC[AES256_GCM,data:5l2lN/hbw98/VCtSjsQ=,iv:n23iZz6ZR+N/Z8wZ+Oenhi3J9lZSRxvW+8n8d8M82Yw=,tag:pEvSfLgM8Ti89K0aQhIuWQ==,type:str]
    UNIFI_HOST: ENC[AES256_GCM,data:SN7OoShtj72UBTI=,iv:QDX7N3mDIl0oNcWwt4cI2pIfF1ZNRqv9VlsDbUIo4HQ=,tag:IWuWFSGbFUHFQ+E2zv7BbA==,type:str]
    UNIFI_API_KEY: ENC[AES256_GCM,data:S/cOqFsHDyhbPDDENGzEOWj6/94RVI43sJ2m+kAcUxc=,iv:f7akgGrzs25ub0m8aiR7rOwqSiBpVxpt35eMXaqdcWw=,tag:r/K7Q+yLY/t+7jIAtih07A==,type:str]
    PSURL: ENC[AES256_GCM,data:51CXc02MbhahYhFrdd+IvvjFuAeUt1s=,iv:2hPx4OkCKYPiHcJuYXMXhTYCbYPe0wYswb3KOWGs+GI=,tag:VFVgjyeii7mxKEY62Vhldg==,type:str]
    PSADMINU: ENC[AES256_GCM,data:DEpor+U=,iv:zFwcbW5YF+HGnR9FW2wCsNAfTdzDJlqmNfnn4Nwj2ls=,tag:sI8b+jyt8uNn+Z/pyyINhQ==,type:str]
    PSADMINP: ENC[AES256_GCM,data:Wp29eYqUqmuHwuH7Zw8qbt1sBA==,iv:kv5VngJdUnv+dJeR02CiIAuqBwUPR8gHibivXUuT8y8=,tag:/owW3Lmnk7UUowChVfl6aw==,type:str]
    PSADMINE: ENC[AES256_GCM,data:F5d787Bh2KbdiQG30w18mX6PyJ7Y,iv:fHT11txnUDoEJwDfIsC7drER5zgE+yourww5btuRuec=,tag:7LfdWcH2qUPDuxWmE8Ge4g==,type:str]
    OIDC_LOGOUT_URL: ENC[AES256_GCM,data:WsCmJlZf766wwKT1bvzRQCbePZlyiyA1CG+v4vuHVPgZ+QHbK6pGi0gHJbY=,iv:DG+RPVfE2Svaj10BX2dLn4/de6Rh7NJYLWNmCldbAXM=,tag:PWjxgxLmqYFkOz4eTcnIPA==,type:str]
    OIDC_AUTH_URL: ENC[AES256_GCM,data:sbWHQ+tZSeznnQIqCgkQbVlZHlcU7Fj9Ed5alO60grxD,iv:Ez/3Ky7BtHH6/TA7+eQ58VjCtaL3jwAHP849EsPENAA=,tag:+V2h9FUazMRrNNwD5HEQ4w==,type:str]
    OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:5qsxIZtjGL4G5+xrfxPv86gyvKbNeTit22XWehQI2lo6MMBwhAiQ/Y+FKcJ/rxr1JwxNVbUWlgI=,iv:OHfZienYbQUqbon8HTdus3hUntRtNdmrC/tq3FMW2rI=,tag:ENNFZHazQfKetS3Z8oZnEg==,type:str]
    OIDC_TOKEN_URL: ENC[AES256_GCM,data:/2Wxo/WFhQWlb6Gseouax3R8b87o2i9alGTY/R8FlRQ192T8N08=,iv:SfJ4ueZU/I8akPuaNpjx+f9bbgRwWQTZlNVDIeBhJFk=,tag:5mxs44XNYAaAXcQt8sxmjA==,type:str]
    OIDC_USERINFO_URL: ENC[AES256_GCM,data:UFNrn/AOTO/qWeeR5sxzhfVo0dGFgGPG1cZyNtF+E2tCO4F9dGx99Rk=,iv:IK+3lQlqmJEd81WZyP4Opy9bdJ8v0aHQSo3pHcRMwVw=,tag:2H7jAkhCM0Qy+bzT1ijmpw==,type:str]
    OIDC_CERTIFICATE_URL: ENC[AES256_GCM,data:c8VvfT8aadZ1L0fMqlxROK8j8fiokBR8xSwYM6crgs7UNkfu0P3R9R5G94AD,iv:FgJLLC3R1l2A7Jhlkhbxq19ELi95KSXId1EjEBsWpQ0=,tag:u3JXlCymcIhV3lr3MHhjqw==,type:str]
    MEALIE_OIDC_CLIENT: ENC[AES256_GCM,data:uGIfZCIHMu1u0L9TLFtOdjL3FS8LaBOKh4sSorbWeK87D0HY,iv:b1kjqRqYGDgT1Jc5L5ZHhmw/FAL+rWI1Xse/8/Wksqo=,tag:bED/iLLmr6Dnj+v0nl9zFA==,type:str]
    MEALIE_OIDC_SECRET: ENC[AES256_GCM,data:PUfu5I3xeuMox3dEXXFhY/cA435ergI4hJOSnWjmIf0=,iv:NbV4ScrR8kpZww7evytqECnK9EpNxD2NZVNS7ASCWi8=,tag:I09ym+9HiZI48zeB4BGt1w==,type:str]
    INFISICAL_CID: ENC[AES256_GCM,data:E99Kd49enk4sJwHw/i8wvgdE29hr2bqYvmnCOzfimmVH2Ht5,iv:g+wPiuuQoyCCcrcoCvxriYnB/CGpKazWP/yJhP3zj8I=,tag:UmRxDzqArs4JkRi9kg/yBg==,type:str]
    INFISICAL_CSECRET: ENC[AES256_GCM,data:oQXn8vz+8bMu/ysUPgXakgGj4fhJKNS2nrxcgwUt1AhAgPaGH8ehPFALt2SuWSxgkIP11RygEy6UF0Llp3v7HA==,iv:EJ8PU+6e1GbgRqhDtjlXYDwqL9QUHBaELMyk9T44oLE=,tag:wEx7XLBIz7pUsExf57nqJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc0NVVzhmUC9SK1FIeDZM
            WnN3UVdhMWxJWkw2dlBrRWltcGltZHNGM0N3CmJXUEtmYVpzTElqK0Vyd0tuKzRv
            ZGE2WVdkM0pzUlJwWStxdkJvNm50VnMKLS0tIE1EOVhuRDJDdEtxdDlaQ2Vpcy9N
            c242VDE2K1FEb0I4bGFGQjBOVDhwb1kKwzpk0lwJBlPiJDn0fg8CawxAxuA16X7g
            ZpUAdAJA7hbCmcbrvpruyZfbur94pKGPWLYbsb5IkV4Ie/ChWD6/GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T13:20:44Z"
    mac: ENC[AES256_GCM,data:0jy7k+DmTSfe7TkcLyg/4n9tJBlY8kdp/TMHMUPivsIcF9aMyyXgUGBrM82OCrEcvyg0AgDu/ySLSzJCYGa07UGZ4Yk1uE6P61455hrSSb2nwQfMCeZx3dg/oG2LoPE63uvC3G3Jxo1y9oh66GRDLttoaOI5nGaAxPHj6KY8LAc=,iv:LEFfGvlenERxrEBVEreS24KCiK0vWFbBe+zD1fVUyp4=,tag:2evZnm10HJt4W66HUg7teA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
