apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:u/Y8PsiK7UcBThXfm0ZCWfk6YkhxPcFNukLoojmEH5yqWDd0WwqGRA==,iv:VRynT0gjD2z9tap40qjDsXze+8PVc70cr+kAgblGPpg=,tag:y1eD1ZHPQyUEEEW81wp7Tw==,type:str]
sops:
    age:
        - recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMVRnaUYxU2VHZDUxWng4
            eXRWN1liVkFoQ2x0UzJoRldkaWZKZUJjK2lBCjVkd1Q2UFJ0U3hXSnI1VmtRM0Ux
            M1U0OERqcm9wTitLRWo3eWpDQlk4cFkKLS0tIDZZVmV5WWpHTitHaEhuaGgwQVdF
            SEdjV0FZM3hCTWllMW5JR0hjN0QxWjgKvrDlIrHMNSuBzjTIzWAJMjbcsNdQ8csC
            vMNtFHKcoJsYz5IZ5noQ8snPgXoMVbz91s6NcpAhYdWYeZxlQruOpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T17:39:40Z"
    mac: ENC[AES256_GCM,data:rbc2YVTEYuGQvBpjiwV/hzp/d6sfvCui+bO0OGe70vfxzx0a7DLczwie27ISAajOAcKvahcWyhGmcsRGLody+ilt0BbTCtk7pwSPg6eI3Ymk0csTG4BPq2/3350BOOs9NfEzu41IKZixj42nz6RYNLaRLzfui5oz/IuZsAfA8+4=,iv:NUeKorelxseTb1PTfX5IpvLxwk0OzE9CVI9XRj0v/Fo=,tag:ZFfyiSF6aDHt7QVkwPujUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
