---
# yaml-language-server: $schema=https://schema.maverickd650.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-secret
  data:
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: GF_ADMIN_PASSWORD
    - secretKey: client-id
      remoteRef:
        key: GRAFANA_OIDC_CLIENT_ID
    - secretKey: client-secret
      remoteRef:
        key: GRAFANA_OIDC_CLIENT_SECRET
    - secretKey: auth-url
      remoteRef:
        key: POCKET_AUTH_URL
    - secretKey: token-url
      remoteRef:
        key: POCKET_TOKEN_URL
