---
apiVersion: v1
kind: Service
metadata:
  name: garage
spec:
  ports:
    - name: http
      protocol: TCP
      port: 30188
      targetPort: 30188
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: garage
  labels:
    kubernetes.io/service-name: garage
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 30188
endpoints:
  - addresses:
      - "${truenasip}"
    conditions:
      ready: true
      serving: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: garage
  annotations:
    external-dns.kubernetes.io/hostname: &host s3.${SECRET_DOMAIN}
spec:
  hostnames:
    - *host
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: garage
          namespace: network
          port: 30188
