---
# yaml-language-server: $schema=https://schema.maverickd650.dev/postgresql.cnpg.io/clusterimagecatalog_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-minimal-trixie
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: minimal
    images.cnpg.io/os: trixie
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.3-minimal-trixie@sha256:ddcf374ba6f66bfa38465c2408b039aed19843c048b60772429713327e902682
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.9-minimal-trixie@sha256:945021c544177c461162ccbc64a354625d6e88c2aa754bd601584a13fa2a94ab
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.13-minimal-trixie@sha256:30f296c24d8ca9ffd84b606e71d32c0093c34262d6e1418fa45ded79e2a5ebde
