---
# yaml-language-server: $schema=https://schema.maverickd650.dev/postgresql.cnpg.io/clusterimagecatalog_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-minimal-trixie
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: minimal
    images.cnpg.io/os: trixie
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.4-minimal-trixie@sha256:e14f3ed42b14f3abeefc56468af42deb2abc3d9eddf2c465b875b2f0ec3ce3f6
      extensions:
        - name: pgvector
          image:
            reference: ghcr.io/cloudnative-pg/pgvector:0.8.2-18-trixie@sha256:d9399ded5a46293ba24a7ddf1e2f630d6e486dd41d3099d731c5715341a97aa1
        - name: postgis
          image:
            reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.2-18-trixie@sha256:94f178eef719e84ce70c18b27290084f8203a2f8900fd1ebeaf9f1c00bfc12e3
          ld_library_path:
            - system
          env:
            - name: GDAL_DATA
              value: ${image_root}/share/gdal
            - name: PROJ_DATA
              value: ${image_root}/share/proj
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.10-minimal-trixie@sha256:f5a180cf01aa3a206957cfe05bf6046de2f925e90952b8c24ed409c05e93df80
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.14-minimal-trixie@sha256:661278ed6c24114efd4893f5ada076a95d5f85472d825d3939eb0ada9ef0cb11
