---
# yaml-language-server: $schema=https://schema.maverickd650.dev/postgresql.cnpg.io/clusterimagecatalog_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-minimal-trixie
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: minimal
    images.cnpg.io/os: trixie
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.3-minimal-trixie@sha256:9763190ed6207aa900ee762de66cc65922f6f34d1335f7c863dd7255ba147bce
      extensions:
        - name: pgvector
          image:
            reference: ghcr.io/cloudnative-pg/pgvector:0.8.2-18-trixie@sha256:d9399ded5a46293ba24a7ddf1e2f630d6e486dd41d3099d731c5715341a97aa1
        - name: postgis
          image:
            reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.2-18-trixie@sha256:94f178eef719e84ce70c18b27290084f8203a2f8900fd1ebeaf9f1c00bfc12e3
          ld_library_path:
            - system
          env:
            - name: GDAL_DATA
              value: ${image_root}/share/gdal
            - name: PROJ_DATA
              value: ${image_root}/share/proj
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.9-minimal-trixie@sha256:256a619a9830b9dbb80183851826327e8230d4367ae6c72c4c90d01a3dd47286
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.13-minimal-trixie@sha256:9294f428576bb3e05ae2ed15dfa485c172723c823b8104f6ec2b264b3ad78d35
