---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mavbot-pem
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: mavbot-pem
  data:
    - secretKey: private_key_pem
      remoteRef:
        key: MAVBOT_PEM
