apiVersion: v1
kind: Secret
metadata:
  name: ghcr-feedcord
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:NHWYzeKbLgoTDwRUrNHcev+z0kWP/8XfaxbKv8shPvLyw10oOeN5Url/lHfsLkD9koMLQ5ev9K60Ct/EZ4kZ9oLUpsbAxCywHN1h8U0t5KRrX6KQ0qhvG90JM9V6kSo2aNa1QLS8wfndpigs1nufnErqRIXXt9IQi/7lGPm5OWuQqv5PHtRVZ9AKvIX6dIZMwX6jyAIHNcZvrd2KTfTKmtAA78mBYvmChTKLYYctFLIYgdmgpeH/U0CdAA1lnXhGxArAksQj2IGnCWiqs6ZJKQc/gnrBTj0yoX2Mr9Zmzg98hZ87vjrGY8wSt85VQlE3K25C8mlAKUo=,iv:t8e3WEIi2yKNOWpfu8Mxf+NA4e6hktwuZ66RQ2doozA=,tag:Hfk8faYx3bax1fHVbNSUtg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdEd4eDVCYVFNKzh6anNB
        R0tmVTJkaUQvRDRPcXV2OVpkcjBUSVlBMjBRClNhdFh1d1ZQbVJxTmhLMzVXZURn
        ekIxYWJxUEhFWGpFdDVGVngxSGgzTGcKLS0tIEZmQ2JiUmZGTDF1Z3JzRC9yemUv
        VG84em1NNWw0dHN5aUdXTmtVQTF2MmcKz4vkRMH/bSadGWziYhukargKugq8eliA
        FPbG464tba+S0M0kZVi5RlpvO+4OCY4JtPlsTfDNy2ukRXRUX4LIeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T12:02:31Z"
  mac: ENC[AES256_GCM,data:UuKKCCG1JnfLEKPCkRgrpeZ/fNdi2jF0v78ZTGjDTTunEiNqjwKLRWHTjonHkM6bgKlyAmgwIzIh8mlTZBvruIRmmKqwU77hvv6F/TopMtPAWdcg9aEzZhljQLJakxwv3QnR8AL/KeNYC3pmLSkCNqueyR3kXx6ZoE271WH3Q2w=,iv:O0q2rPVsjqrg0fR+jEuLqRZohl6Qp/M+FqP90YsG6ZU=,tag:7iwAYsyGkctGnYPfR8hgJw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
