---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: b2
spec:
  backend:
    b2:
      bucket: M650-kopia
      auth:
        secretRef:
          name: kopiur-nas-secret
  encryption:
    passwordSecretRef:
      name: kopiur-nas-secret
      namespace: kopiur-system
      key: KOPIA_PASSWORD
  create:
    enabled: true
  allowedNamespaces:
    all: true
  identityDefaults:
    hostnameExpr: namespace
    usernameExpr: namespace + '-' + policyName
  moverDefaults:
    securityContext:
      runAsUser: 568
      runAsGroup: 568
    podSecurityContext:
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    ttlSecondsAfterFinished: 86400
  maintenance:
    enabled: true
