---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-nas
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: kopiur-nas-secret
  data:
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: /backup/KOPIA_PASSWORD
    - secretKey: B2_KEY_ID
      remoteRef:
        key: /backup/B2_KEY_ID
    - secretKey: B2_KEY
      remoteRef:
        key: /backup/B2_KEY
