---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage-temp
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: homepage-temp
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.12.3@sha256:cc84f2f5eb3c7734353701ccbaa24ed02dacb0d119114e50e4251e2005f3990a
            env:
              HOMEPAGE_ALLOWED_HOSTS: &host "home-temp.${SECRET_DOMAIN}"
              TZ: Europe/London
            resources:
              requests:
                cpu: 10m
                memory: 350M
              limits:
                memory: 350M
    service:
      main:
        ports:
          http:
            port: 3000
    route:
      internal:
        hostnames: [*host]
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: homepage-temp-config
        globalMounts:
          - path: /app/config
    serviceAccount:
      homepage: {}
