---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
spec:
  isCA: true
  commonName: cluster-ca
  subject:
    countries:
      - UK
    organizations:
      - maverickd650
  usages:
    - cert sign
    - crl sign
  duration: 87660h
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Never
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: cluster-ca-cert
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-ca
spec:
  ca:
    secretName: cluster-ca-cert
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-server-ca
spec:
  isCA: true
  commonName: postgres-server-ca
  subject:
    countries:
      - UK
    organizations:
      - maverickd650
  usages:
    - cert sign
    - crl sign
  duration: 87660h
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Never
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  secretName: postgres-server-ca-cert
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: postgres-server-ca
spec:
  ca:
    secretName: postgres-server-ca-cert
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-client-ca
spec:
  isCA: true
  commonName: postgres-client-ca
  subject:
    countries:
      - UK
    organizations:
      - maverickd650
  usages:
    - cert sign
    - crl sign
  duration: 87660h
  privateKey:
    algorithm: ECDSA
    size: 384
    encoding: PKCS8
    rotationPolicy: Never
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    labels:
      cnpg.io/reload: ""
  secretName: postgres-client-ca-cert
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: postgres-client-ca
spec:
  ca:
    secretName: postgres-client-ca-cert
