---
# yaml-language-server: $schema=https://schema.maverickd650.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chartRef:
    kind: OCIRepository
    name: common
    namespace: system
  interval: 1h
  timeout: 20m
  maxHistory: 3
  upgrade:
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      plex:
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/plex
              tag: 1.43.2.10687@sha256:29aea09831a2b008ffa36b9d71b52aaf1fa3feeedec5f0211c991de01a70f645
            env:
              ALLOWED_NETWORKS: "172.16.0.0/12,10.0.0.0/8,192.168.0.0/16"
              TZ: Europe/London
              PLEX_ADVERTISE_URL: "https://plex.${SECRET_DOMAIN},https://plex.${SECRET_DOMAIN}:32400,http://192.168.20.1:32400"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    service:
      app:
        type: LoadBalancer
        controller: plex
        ports:
          http:
            enabled: true
            port: 32400
            protocol: TCP
            targetPort: 32400
    route:
      app:
        hostnames:
          - "plex.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: plex-config
      stash1:
        type: nfs
        path: /mnt/media/stash/misc
        globalMounts:
          - path: /data/stash1
        server: 192.168.50.118
      stash2:
        type: nfs
        path: /mnt/media/stash-rm
        globalMounts:
          - path: /data/stash2
        server: 192.168.50.118
      media:
        type: nfs
        path: /mnt/media/mediashare
        globalMounts:
          - path: /data/media
        server: 192.168.50.118
