---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rss2discord-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: rss2discord-secret
  data:
    - secretKey: tech-webhook
      remoteRef:
        key: rss2discord/discord_tech_webhook
    - secretKey: hobbies-webhook
      remoteRef:
        key: rss2discord/discord_hobbies_webhook
    - secretKey: releases-webhook
      remoteRef:
        key: rss2discord/discord_releases_webhook
