---
apiVersion: rss2discord.maverickd650.dev/v1alpha1
kind: FeedGroup
metadata:
  name: tech-news-test
  namespace: default
spec:
  discordWebhookSecretRef:
    name: rss2discord-secret
    key: tech-webhook
  interval: "30m"
  retries: 3
  retryInterval: "5m"
  embed:
    enabled: true
    color: "#5865F2"
  feeds:
    - rssUrl: "https://www.theguardian.com/uk/rss"
