---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rss2discord
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rss2discord
  upgrade:
    cleanupOnFail: true
  values:
    prometheus:
      enabled: true
    prometheusRule:
      enabled: true
    grafanaDashboard:
      enabled: true
      allowCrossNamespaceImport: true
      instanceSelector:
        matchLabels:
          grafana.internal/instance: grafana
