---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/fluxcd.controlplane.io/resourceset_v1.json
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: alerts-status
  namespace: system
spec:
  dependsOn:
    # Wait for ExternalSecrets and ClusterSecretStore to be ready before applying alerts
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-secrets
      namespace: security
      ready: true
    - apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      name: infisical
      namespace: security
      ready: true

  # Health checks - wait for generated resources to be ready
  wait: true

  inputs:
    - namespace: "cert-manager"
    - namespace: "flux-system"
    - namespace: "jobs"
    - namespace: "kube-system"
    - namespace: "longhorn-system"
    - namespace: "media"
    - namespace: "network"
    - namespace: "observability"
    - namespace: "security"
    - namespace: "system"
  resources:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      metadata:
        name: github-status-token-secret
        namespace: << inputs.namespace >>
      spec:
        secretStoreRef:
          kind: ClusterSecretStore
          name: infisical
        target:
          name: github-status-token-secret
        data:
          - secretKey: githubAppID
            remoteRef:
              key: GITHUB_APP_ID
          - secretKey: githubAppInstallationID
            remoteRef:
              key: GITHUB_APP_INSTALLATION_ID
          - secretKey: githubAppPrivateKey
            remoteRef:
              key: MAVBOT_PEM
    - apiVersion: notification.toolkit.fluxcd.io/v1beta3
      kind: Provider
      metadata:
        name: github-status
        namespace: << inputs.namespace >>
      spec:
        type: github
        address: https://github.com/maverickd650/home-operations
        secretRef:
          name: github-status-token-secret
    - apiVersion: notification.toolkit.fluxcd.io/v1beta3
      kind: Alert
      metadata:
        name: github-status
        namespace: << inputs.namespace >>
      spec:
        providerRef:
          name: github-status
        eventSources:
          - kind: Kustomization
            name: '*'
