apiVersion: v1
kind: Secret
metadata:
  name: ghcr-homepage
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:v3aouD6bbtzINEnCnZqjkTzsQg+nGN35KljzubbOtwh+jtoey4aOq0XjRpTiYr4e/k9O8hKshKi9/E3HuN1l0ulXPNpKtl4nPdYq2y8AJfQX7Y8ewyPgsQfl5jJBl4aYEFlZOjgxNKyBqFCRuEHyWy2Q9cOzV6aBUw2ZnSUA7449oe89phH5NZPJs2+tLmZNTNq6OAQafxEBbZNo9KY9khKS1E8yHqSXoaRmBNmizGn78m7F+zIKsrsNGpw3rjiGE4JR3rtPDYwL8gJ3yfyJzlISnddIKRsRXltdFpUUNhm+KH3u+9DYNUk6X6ifxjtsdGR4MnT2ino=,iv:N+XxhED3NTUA2V395OtSayLJzae/abNqkC2Fxv4zCz0=,tag:/ujBy2kRlMcrrtixQMdctw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYUd3ZVhTU0pNT3FlblEv
        M3QwRXNwSmFXa1N1ZlZHRVdXWHNkK1pia2hRCjVjeHB4MHVBZ1VpbXJBR00relBK
        L2EvS2FrN3ZmWXU4OTd1Z2xUQkZUS1UKLS0tIHhQaGZlM05Wd0pIaWNWWW1GbDM0
        aWpScXdhckRjYW1hZ1VReGNlYXZLMjgK1QLmSZnIjFm6HO+Hr0kx8UpGNrT+zhh9
        OfUksPqZGleBoGOuecUkh4dEzlDkx9CxNkx08nRlHhHmb3UgDt3E6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17m9m7pxlc2mps7vc3t4j78sanhs0yjhl7jt340sffwtf264u6c2q7dsw4z
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T11:40:01Z"
  mac: ENC[AES256_GCM,data:J7AR4yyWd2TMpr6JWYUvcWYhRmpqlGeVrH8fLTnv7n9/78lhNwK/LwAmU/tvaErT9OXcOaYPNkdeEiY/ERTZUsUSBo72eZ1DGSU+OeOdXAy0A7meQ0ol7+CcGQvew5yjysYe9Am94VjES2aHYuXkpC1b8VqHKGjKXTi8/9nf8GM=,iv:9UYm7DmPFpT2+HboC0H7ZOf62ESG9udMYZ8HoERYA2M=,tag:HY6BRn5Vb3PN48Lx2jMIiQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
