---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filebrowser-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: filebrowser-secret
  data:
    - secretKey: FILEBROWSER_ADMIN_PASSWORD
      remoteRef:
        key: FB_PASS
    - secretKey: FILEBROWSER_OIDC_CLIENT_ID
      remoteRef:
        key: FB_CID
    - secretKey: FILEBROWSER_OIDC_CLIENT_SECRET
      remoteRef:
        key: FB_CSECRET
