---
# yaml-language-server: $schema=http://schema.maverickd650.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: garage-secret
  data:
    - secretKey: GARAGE_RPC_SECRET
      remoteRef:
        key: GARAGE_RPC_SECRET
    - secretKey: GARAGE_ADMIN_TOKEN
      remoteRef:
        key: GARAGE_ADMIN_TOKEN
