---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: feedcord
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: feedcord
  interval: 1h
  path: ./kubernetes/apps/default/feedcord/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  dependsOn:
    - name: feedcord-config
      namespace: default
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: feedcord-config
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: feedcord
  interval: 1h
  prune: true
  sourceRef:
    kind: OCIRepository
    name: feedcord-config
  targetNamespace: default
  wait: false
