---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: pocket-secret
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: PID_ENCRYPTION_KEY
