---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: paperless-ngx-cnpg-main
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": paperless-ngx-cnpg-main
  podMetricsEndpoints:
    - port: metrics
      scheme: http
      tlsConfig:
        ca:
          secret:
            name: paperless-ngx-cnpg-main-ca
            key: ca.crt
        serverName: paperless-ngx-cnpg-main-rw
