---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./prometheusrule.yaml
  - ./resourceset-backups.yaml
  - ./resourceset-input.yaml
  - ./resourceset-pvcs.yaml
