---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Package Cleanup"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old GHCR images
    permissions:
      contents: read
      packages: write # for deleting packages
    environment:
      name: bot
      deployment: false
    steps:
      - uses: snok/container-retention-policy@d3bdcf5ce9b05f685154e4a16c39233b245e3d53 # v3.1.0
        with:
          account: user
          token: ${{ secrets.GHCR_PAT }}
          image-names: "home-operations"
          cut-off: 1w
          dry-run: false
